name: Auto Merge

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  auto-merge:
    uses: Adamantine-guild/.github/.github/workflows/auto-merge.yml@main
    secrets:
      AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
